# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: none

pages:
  script:
  - apk add git
  - git submodule sync themes/ananke
  - git submodule update --init themes/ananke
  - hugo mod graph
  - hugo --logLevel debug --minify
  artifacts:
    paths:
    - public
  only:
  - master
