baseURL = "https://retrobian.org.uk/"
title = "Retrobian"
languageCode = "en-GB"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"

[params]
subtitle = "Retro Debian installations"
featured_image = "/install/0.93-debian-login.png"
recent_posts_number = 10
custom_css = ["custom.css"]

[author]
name = "Thomas Stewart"
email = "thomas@stewarts.org.uk"

[module]
[[module.imports]]
path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
