#!/bin/bash -eux
mode=$1
version=$2
shift
shift
opts="$@"

case $version in
"0.91")
        release="debian"
        releasedir="debian-0.91"
        ;;
"0.93")
        release="debian"
        releasedir="Debian-0.93R6"
        ;;
"1.1")
        release="buzz"
        releasedir="$release"
        opts="--device isa-serial,chardev=serial0 --chardev msmouse,id=serial0"
        ;;
"1.2")
        release="rex"
        releasedir="$release"
        ;;
"1.3")
        release="bo"
        releasedir="$release"
        ;;
"2.0")
        release="hamm"
        releasedir="$release"
        ;;
"2.1")
        release="slink"
        releasedir="$release"
        ;;
"2.2")
        release="potato"
        releasedir="$release"
        ;;
"3.0")
        release="woody"
        releasedir="$release"
        ;;
*)
        exit
        ;;
esac

if [ "$mode" == "clean" ]; then
        rm *.qcow2 *.img
        exit
fi

if [ "$mode" == "genrepo" ]; then
        mkdir -p retrobian-repo/$version-$release-repo
        if [ "$version" == "0.91" ]; then
                lftp -e "mirror --delete --only-missing --verbose . retrobian-repo/$version-$release-repo; exit" \
                        http://www.ibiblio.org/pub/historic-linux/distributions/debian-0.91/
        else
                rsync -av --delete \
                        archive.debian.org::debian-archive/debian/dists/$releasedir/. \
                        retrobian-repo/$version-$release-repo/.
        fi
        if [ "$version" == "2.1" -o "$version" == "2.2" -o "$version" == "3.0" ]; then
                rsync -av \
                        archive.debian.org::debian-archive/debian-non-US/dists/$release/. \
                        retrobian-repo/$version-$release-repo/
        fi

        reposize=$(du -skc retrobian-repo/$version-$release-repo files | tail -1 | awk '{print $1}')
        reposize=$(echo "($reposize * 1.2) / 1024" | bc -l | awk -F. '{print $1}')

        qemu-img create -f qcow2 retrobian-repo/$version-$release-repo.qcow2 ${reposize}M
        sudo modprobe nbd max_part=63
        sudo qemu-nbd -c /dev/nbd0 --cache=writeback retrobian-repo/$version-$release-repo.qcow2
        sudo parted /dev/nbd0 mklabel msdos
        sudo parted /dev/nbd0 mkpart pri 1 100%
        sudo mkfs.ext2 -r 0 /dev/nbd0p1
        #sudo mkfs.ext2 -b 1024 -r 0 -i 4096 -F /dev/nbd0p1
        #sudo tune2fs -E hash_alg=legacy /dev/nbd0p1
        mkdir -p retrobian-repo/$version-$release-repo.qcow2.d
        sudo mount /dev/nbd0p1 retrobian-repo/$version-$release-repo.qcow2.d
        sudo rsync -a retrobian-repo/$version-$release-repo/. retrobian-repo/$version-$release-repo.qcow2.d/.

        if [ "$version" == "1.1" ]; then
                (cd retrobian-repo/$version-$release-repo.qcow2.d; ln -s main stable)
                (cd retrobian-repo/$version-$release-repo.qcow2.d/main; ln -s binary-i386 binary)
                (cd retrobian-repo/$version-$release-repo.qcow2.d/contrib; ln -s binary binary-i386)

                sudo cp retrobian-repo/$version-$release-repo/main/disks-i386/1996_6_16/base1_1.tgz \
                        retrobian-repo/$version-$release-repo.qcow2.d/
        fi
        if [ "$version" == "1.2" ]; then
                (cd retrobian-repo/$version-$release-repo.qcow2.d; ln -s main stable)

                sudo cp retrobian-repo/$version-$release-repo/main/disks-i386/current/base1_2.tgz \
                        retrobian-repo/$version-$release-repo.qcow2.d/
        fi
        if [ "$version" == "1.3" ]; then
                (cd retrobian-repo/$version-$release-repo.qcow2.d; ln -s main stable)
        fi
        if [ "$version" == "2.2" ]; then
                sudo cp retrobian-repo/$version-$release-repo/main/disks-i386/current/base2_2.tgz \
                        retrobian-repo/$version-$release-repo.qcow2.d/
        fi
        if [ "$version" == "3.0" ]; then
                echo todo
        fi

        cp -a files retrobian-repo/$version-$release-repo.qcow2.d/
        df -h retrobian-repo/$version-$release-repo.qcow2.d
        sudo umount retrobian-repo/$version-$release-repo.qcow2.d
        rmdir retrobian-repo/$version-$release-repo.qcow2.d
        sudo qemu-nbd -d /dev/nbd0
        qemu-img convert -p -c -O qcow2 retrobian-repo/$version-$release-repo.qcow2 \
                retrobian-repo/$version-$release-repo.qcow2.new
        mv      retrobian-repo/$version-$release-repo.qcow2.new \
                retrobian-repo/$version-$release-repo.qcow2
        exit
fi

if [ "$mode" == "build" ]; then
        rm -f   $version-$release.fda.img \
                $version-$release.fdb.img \
                $version-$release.qcow2 \
                retrobian-repo/$version-$release-repo.qcow2 \
                retrobian-img/$version-$release.qcow2
        $0 $version genrepo

        if [ "$version" == "0.91" ]; then
                qemu-img create -f qcow2 retrobian-img/$version-$release.qcow2 200M
        else
                qemu-img create -f qcow2 retrobian-img/$version-$release.qcow2 1G
        fi

        if [ "$version" == "0.91" ]; then
                zcat debian-0.91/dist/base/bootdisk.gz \
                        > $version-$release.fda.img
                zcat debian-0.91/dist/base/basedsk1.gz \
                        > $version-$release.fdb.img
        fi

        if [ "$version" == "0.93" ]; then
                zcat retrobian-repo/$version-$release-repo/disks/1440_boot_floppy.gz \
                        > $version-$release.fda.img
                zcat retrobian-repo/$version-$release-repo/disks/1440_root_floppy.gz \
                        > $version-$release.fdb.img
        fi

        if [ "$version" == "1.1" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/1996_6_16/boot1440.bin \
                        $version-$release.fda.img
                cp retrobian-repo/$version-$release-repo/main/disks-i386/1996_6_16/root.bin \
                        $version-$release.fdb.img
        fi
        if [ "$version" == "1.2" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/resq1440.bin \
                        $version-$release.fda.img
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/drv1440.bin \
                        $version-$release.fdb.img
        fi
        if [ "$version" == "1.3" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/resc1440.bin \
                        $version-$release.fda.img
        fi
        if [ "$version" == "2.0" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/resc1440.bin \
                        $version-$release.fda.img
        fi
        if [ "$version" == "2.1" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/resc1440.bin \
                        $version-$release.fda.img
        fi
        if [ "$version" == "2.2" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/images-2.88/rescue.bin \
                        $version-$release.fda.img
        fi
        if [ "$version" == "3.0" ]; then
                cp retrobian-repo/$version-$release-repo/main/disks-i386/current/images-2.88/rescue.bin \
                        $version-$release.fda.img
        fi

        opts="$opts --boot a"
        opts="$opts --device floppy,drive=floppy0,unit=0"
        opts="$opts --blockdev driver=file,node-name=floppy0,filename=$version-$release.fda.img"
        if [ -f $version-$release.fdb.img ]; then
                opts="$opts --device floppy,drive=floppy1,unit=1"
                opts="$opts --blockdev driver=file,node-name=floppy1,filename=$version-$release.fdb.img"
        fi
fi

if [ "$mode" == "deflate" ]; then
        sudo modprobe nbd max_part=63
        sudo qemu-nbd -c /dev/nbd0 --cache=writeback retrobian-img/$version-$release.qcow2
        mkdir -p $version-$release.qcow2.d
        sudo mount -t ext2 /dev/nbd0p1 $version-$release.qcow2.d
        sudo dd if=/dev/zero of=$version-$release.qcow2.d/zzz bs=1M || true
        sudo rm -f $version-$release.qcow2.d/zzz
        sleep 2
        sudo umount $version-$release.qcow2.d
        rmdir $version-$release.qcow2.d
        sudo qemu-nbd -d /dev/nbd0
        qemu-img convert -p -c -O qcow2 retrobian-img/$version-$release.qcow2 \
                retrobian-img/$version-$release.qcow2.new
        mv retrobian-img/$version-$release.qcow2.new retrobian-img/$version-$release.qcow2
        exit
fi

hd="$version-$release.qcow2"
if [ ! -f $hd -a -f retrobian-img/$hd ]; then
        qemu-img create -f qcow2 -b retrobian-img/$hd $hd
elif [ ! -f $hd ]; then
        qemu-img create -f qcow2 -o backing_file="json:{\"file.driver\":\"https\",,\"file.timeout\":\"10\",,\"file.url\":\"https://img.retrobian.org.uk/retrobian-img//$hd\"}" $hd
fi
opts="$opts --device ide-hd,drive=ide0-hd0,bus=ide.0,unit=0"
opts="$opts --blockdev qcow2,node-name=ide0-hd0,file.driver=file,file.filename=$hd,cache-size=$(( 256*1024*1024 ))"

if [ -f retrobian-repo/$version-$release-repo.qcow2 ]; then
        opts="$opts --device ide-hd,drive=ide0-hd1,bus=ide.0,unit=1"
        opts="$opts --blockdev qcow2,node-name=ide0-hd1,file.driver=file,file.filename=retrobian-repo/$version-$release-repo.qcow2"
fi

opts="$opts --device ne2k_isa,netdev=net0 --netdev tap,id=net0,script=no,downscript=no"
#opts="$opts --device ne2k_isa,netdev=net0 --netdev user,id=net0,hostfwd=tcp::2323-:23"

opts="$opts --name Debian-$release-$version"
opts="$opts --vga cirrus"

sudo qemu-system-i386 -enable-kvm $opts &
sleep 1
for tap in $(/bin/ip -br link | awk '/^tap/{print $1}' | xargs); do
        sudo ip link set $tap up
        sudo ip link set $tap master virbr0
done
